version: "3"

services:
#  postgres:
#    image: postgres:latest
#    container_name: "gadget_medics_postgres"
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=${DB_USERNAME}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_DB=${DB_DATABASE}
#    volumes:
#      - gadget_medics_postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    environment:
      - MYSQL_ROOT_PASSWORD=Atkqrn8FNZHn
      - MYSQL_PASSWORD=Atkqrn8FNZHn
      - MYSQL_USER=gadgeto0_GMDB
      - MYSQL_DATABASE=gadgeto0_gadgetmedicsdb

  webserver:
    image: abiosoft/caddy
    container_name: "gadget_medics_webserver"
    environment:
      - ACME_AGREE=true
      - CADDYPATH=/etc/caddycerts
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/Caddyfile
      - ./docker/caddy/caddyssl:/etc/caddycerts
      - ./:/app
    depends_on:
      - app

  app:
    build: ./docker/
    container_name: "gadget_medics_app"
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    command: /usr/local/sbin/php-fpm --allow-to-run-as-root

volumes:
  gadget_medics_mysql_data:

networks:
  default:
    external:
      name: gadget-medics-proxy
