<?php
/**
 * Version: 1.0.0
 * WC requires at least: 3.0
 * WC tested up to: 3.9.3
 * Plugin Name: Chaly Stripe and Slack
 * Plugin URI: https://www.chaly.xyz/
 * Description: Integration plugin
 * Author: chaly
 * Author URI: https://www.chaly.xyz/
 * Text Domain: chalycrm
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}
//slack
function api_gadgetMedics_request($url, $posts)
{
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($posts));

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    return $result;
}

function slack_api($text)
{
    //    https://hooks.slack.com/services/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 online
      $webhook =  "https://hooks.slack.com/services/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"; // offline
//    $webhook = "https://hooks.slack.com/services/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";
    return api_gadgetMedics_request($webhook, ["text" => $text]);
}

add_action('wp_ajax_pay_form', 'pay_form_callback');
add_action('wp_ajax_nopriv_pay_form', 'pay_form_callback');


function pay_form_callback()
{
    $name = $_POST['name'];
    $phone = $_POST['phone'];
    $email = $_POST['email'];
    $model = $_POST['model'];
    $color = $_POST['color'];
    $payment = $_POST['payment'];
    if ($_POST['payment'] == 'offline') {
        $message = "
    iPhone Back Glass Repair
    \n
    Name: $name;\n
    Phone: $phone; \n
    Eamil: $email;\n
    Model: $model;\n
    Color: $color;\n
    Payment: $payment;\n
    ";
        print_r(
            slack_api($message));
    }elseif ($_POST['payment'] == 'online'){
        global $wpdb;
        $query = "INSERT INTO `wp_request_form_chaly` (`id`, `name`, `phone`, `email`, `model`, `color`, `pay_status`) VALUES (NULL, '$name', '$phone', '$email', '$model', '$color', '1')";
        $query = $wpdb->query($query);
        $id = $wpdb->insert_id;
        stripe_pay($id);
    }
    wp_die();
}

function stripe_pay($id)
{
    require_once('vendor/autoload.php');

    $stripe = new \Stripe\StripeClient('sk_test_hm2Yenyg0uvS1oBaRgxC1P9H000oMLdZFH');

    try {
        $stripeCheckout = $stripe->checkout->sessions->create([
            'success_url' => 'https://gadgetmedics.com/wp-content/plugins/chaly-stripe/success.php?request_pay_id='.$id,
            'cancel_url' => 'https://gadgetmedics.com/wp-content/plugins/chaly-stripe/cancel.php?request_pay_id='.$id,
            'payment_method_types' => ['card'],
            'line_items' => [[
                'price_data' => [
                    'product_data' => [
                        'name' => "iPhone Back Glass Repair",
                        'metadata' => [
                            'pro_id' => "12"
                        ]
                    ],
                    'unit_amount' => 75,
                    'currency' => "usd",
                ],
                'quantity' => 1,
                'description' => "test description",
            ]],
            'mode' => 'payment',
        ]);
        echo "
     <script>
 var stripe = Stripe('pk_test_Eka8NnaCTGmaEWpHyIMKX0p500qc3MUTKh');
 stripe.redirectToCheckout({
 sessionId: '$stripeCheckout->id'
 }).then(function (result) {
  result.error.message
 });
 </script>
 ";
    } catch (\Stripe\Exception\ApiErrorException $e) {
        echo $e->getMessage();
    }

}